# Generated by Django 4.2.5 on 2024-03-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
