# Generated by Django 4.2.5 on 2024-03-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('consumer_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uploader', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=255)),
            ],
        ),
    ]
