# Generated by Django 4.2.5 on 2024-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsTaken',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('consumer_number', models.CharField(max_length=255)),
                ('uploader', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('last_modified_time', models.TimeField()),
            ],
        ),
    ]
