# Generated by Django 4.2.5 on 2024-03-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_actionstaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstaken',
            name='last_modified_time',
            field=models.DateTimeField(),
        ),
    ]
