# Generated by Django 4.2.5 on 2024-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_actionstaken_last_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstaken',
            name='last_modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
