# Generated by Django 4.2.5 on 2024-06-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_actionstaken_last_modified_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStatus',
            fields=[
                ('user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paymentStatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('user', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
